DeepChecks.WebMVC/Controllers/RelationshipController.cs
using DeepChecks.Models.Relationship;
using DeepChecks.Service;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeepChecks.WebMVC.Controllers
{
    [Authorize]
    public class RelationshipController : Controller
    {
        // GET: Relationship
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new RelationshipService(userId);
            var model = service.GetRelationships();

            return View(model);
        }

        //GET
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RelationshipCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateRelationshipService();

            if (service.CreateRelationship(model))
            {
                TempData["SaveResult"] = "Your relationship was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Relationship could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateRelationshipService();
            var model = svc.GetRelationshipById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateRelationshipService();
            var detail = service.GetRelationshipById(id);
            var model =
                new RelationshipListItem
                {
                    RelationshipId = detail.RelationshipId,
                    RelationshipName = detail.RelationshipName
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, RelationshipListItem model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.RelationshipId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateRelationshipService();

            if (service.UpdateRelationship(model))
            {
                TempData["SaveResult"] = "Your relationship name has been updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your relationship name could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateRelationshipService();
            var model = svc.GetRelationshipById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteARelationship(int id)
        {
            var service = CreateRelationshipService();

            service.DeleteRelationship(id);

            TempData["SaveResult"] = "Your relationship was deleted";

            return RedirectToAction("Index");
        }

        private RelationshipService CreateRelationshipService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new RelationshipService(userId);
            return service;
        }
    }
}

DeepChecks.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Deep Checks</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Syles", required:false)
<style>
    body {
        background-image: url(/Content/Images/pastel-background.jpg);
    }
    wrapper{
        background-color:white;
    }
</style>
</head>
<body>
    @Html.Partial("_Navbar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Deep Checks</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DeepChecks.WebMVC/Views/Shared/_Navbar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top"
     style="background-color:indianred;">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Deep Checks", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("My Relationships", "Index", "Relationship")</li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>